version: '3.8'

services:
  api:
    build:
      context: .
    volumes:
      - .:/src:delegated
    env_file:
      - .env
    command: flask run -h 0.0.0.0
    networks:
      - base-net
#      - app-net
    ports:
      - 5001:5000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - base-net

    env_file:
      - env/.env_postgres.dev


volumes:
  postgres_data:

networks:
  base-net:
#  app-net:



