


FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY react-digesta/package.json react-digesta/package-lock.json .
COPY react-digesta/src ./src
COPY react-digesta/public ./public
RUN npm install
RUN npm run build








FROM nginx

COPY --from=build-step app/build /usr/share/nginx/html
COPY /deployment/nginx.conf /etc/nginx/conf.d/default.conf