version: '3.8'

services:
  myapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/src:delegated
    env_file:
      - .env
#    command: flask run -h 0.0.0.0
    command: gunicorn -c python:config.gunicorn app:app
    networks:
      - base-net
      - app-net
    ports:
      - 5001:5000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - base-net

    env_file:
      - .env_postgres.dev

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx/
      - ./certificates/ssl:/etc/nginx/ssl
    depends_on:
      - myapi
    ports:
      - 443:443
      - 80:80
    networks:
      - app-net


volumes:
  postgres_data:

networks:
  base-net:
  app-net:



