version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/src:delegated
#    env_file:
#      - env/.env.dev
    command: python app.py
#    networks:
#      - base-net
#      - app-net
    ports:
      - 5050:5050

#    depends_on:
#      - db
#
#  db:
#    image: postgres:12-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    networks:
#      - base-net
#
#    env_file:
#      - env/.env_postgres.dev





#
#volumes:
#  postgres_data:
#
#networks:
#  base-net:
#  app-net:



