const authors = {
    "ALFENUS VARUS": "ALFENUS",
    "ARCADIUS QUI ET CHARISIUS": "ARCADIUS CHARISIUS",
    "AURELIUS ARCADIUS CHARISIUS MAGISTER LIBELLORUM": "ARCADIUS CHARISIUS",
    "PAPIRIUS IUSTUS": "IUSTUS PAPIRIUS",
    "HERENNIUS MODESTINUS": "MODESTINUS",
    "QUINTUS MUCIUS SCAEVOLA": "SCAEVOLA",
    "SATURNINUS": "VENULEIUS SATURNINUS",
    "VENULEIUS": "VENULEIUS SATURNINUS"
}