doublets_authors = {
    "ALFENUS": "ALFENUS VARUS",
    "ARCADIUS QUI ET CHARISIUS": "ARCADIUS CHARISIUS",
    "AURELIUS ARCADIUS CHARISIUS MAGISTER LIBELLORUM": "ARCADIUS CHARISIUS",
    "PAPIRIUS IUSTUS": "IUSTUS PAPIRIUS",
    "MODESTINUS": "HERENNIUS MODESTINUS",
    "QUINTUS MUCIUS SCAEVOLA": "SCAEVOLA",
    "SATURNINUS": "VENULEIUS SATURNINUS",
    "VENULEIUS": "VENULEIUS SATURNINUS",
    "MACER": "AEMILIUS MACER",
    "MAECIANUS": "VOLUSIUS MAECIANUS",
    "VALENS": "ABURNIUS VALENS",
    "<ULPIANUS?>": "ULPIANUS"

}

doublets_opera = {
    "ad formulam hypothecariam": "de formula hypothecaria",
    "de legatis ad edictum urbicum": "de legatis ad edictum praetoris urbani",
    "cognitionum": "de cognitionibus",
    "posteriorum Labeonis": "ex posterioribus Labeonis",
    "de fideicommissis": "fideicommissorum",
    "Labeonis posteriorum": "ex posterioribus Labeonis",
    "de iudiciis publicis": "de publicis iudiciis",
    "de iudicis publicis": "de publicis iudiciis",
    "publicorum iudiciorum": "de publicis iudiciis",
    "iudiciorum publicorum": "de publicis iudiciis",
    "de adulteris": "de adulteriis",
    "de testamentis ad edictum praetoris": "de testamentis ad edictum praetoris urbani",
    "de testamentis ad edictum urbicum": "de testamentis ad edictum praetoris urbani",
    "epitomarum Alfeni": "epitomarum Alfeni Vari digestorum",
    "epitomarum Alfeni digestorum": "epitomarum Alfeni Vari digestorum",
    "epitomatorum Alfeni digestorum": "epitomarum Alfeni Vari digestorum",
    "fideicomissorum": "fideicommissorum",
    "iuris epitomatorum": "iuris epitomarum",
    "pithanorum": "pithanon",
    "πιϑανῶν": "pithanon",
    "posteriorum epitomatorum a Iavoleno": "posteriorum a Iavoleno epitomatorum",
    "publicorum": "de publicis iudiciis",
    "rerum cottidianarum sive aureorum": "rerum cottidianarum",
    "rerum cottidianarum vel aureorum": "rerum cottidianarum",
    "cottidianarum rerum": "rerum cottidianarum",
    "aureorum": "rerum cottidianarum",
    "ad edictum urbicum": "ad edictum praetoris urbani",
    "epitomatorum": "epitomarum",
    "iuris epitomarum": "epitomarum",
    "ad Ferocem": "ad Urseium Ferocem",
    "constitutionum": "de constitutionibus",
    "pithanorum a Paulo epitomatorum": "pithanon a Paulo epitomatorum",
    "πιϑανῶν a Paulo epitomatorum": "pithanon a Paulo epitomatorum",
    "de excusatione tutorum": "de excusatione tutorum",
    "variorum lectionum": "ex variis lectionibus",
    "militarium": "de re militari",
    "ad Massurium Sabinum": "ad Sabinum",
    "de officio proconsulis sub titulo de abigeis": "de officio proconsulis",
    "de officio proconsulis sub titulo de furibus": "de officio proconsulis",
    "a Iavoleno epitomatorum posteriorum": "posteriorum a Iavoleno epitomatorum",
    "posteriorum": "posteriorum a Iavoleno epitomatorum",
    "quaestionum titulo a quo fundus petetur si rem nolit": "quaestionum",
    "ad edictum praetoris urbani titulo de liberali causa": "ad edictum praetoris urbani"


}