"""empty message

Revision ID: 2f06eb826d42
Revises: a0f9ce33394e
Create Date: 2023-04-21 18:29:55.384981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f06eb826d42'
down_revision = 'a0f9ce33394e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('private', sa.Boolean(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('paragraphus_id', sa.Integer(), nullable=False),
                    sa.Column('reply_to_comment_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['paragraphus_id'], ['digesta_paragraphi.id'], ),
                    sa.ForeignKeyConstraint(['reply_to_comment_id'], ['comments.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lex_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'digesta_leges', ['lex_id'], ['id'])
        batch_op.drop_column('paragraphus_id')

    # ### end Alembic commands ###
