"""empty message

Revision ID: 4d608a0179d2
Revises: 
Create Date: 2023-04-06 14:47:02.837461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d608a0179d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('flourished_start', sa.Integer(), nullable=True),
    sa.Column('flourished_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('digesta_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_latin_name', sa.String(length=256), nullable=False),
    sa.Column('book_polish_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_latin_name'),
    sa.UniqueConstraint('book_polish_name')
    )
    op.create_table('digesta_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title_lat', sa.String(length=256), nullable=False),
    sa.Column('title_pl', sa.String(length=256), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['digesta_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_lat', sa.String(length=256), nullable=False),
    sa.Column('title_pl', sa.String(length=256), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digesta_paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_lat', sa.Text(), nullable=False),
    sa.Column('text_pl', sa.Text(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('opus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['opus_id'], ['opera.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['digesta_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digesta_paragraphs')
    op.drop_table('opera')
    op.drop_table('digesta_sections')
    op.drop_table('digesta_books')
    op.drop_table('authors')
    # ### end Alembic commands ###
