"""empty message

Revision ID: 5ae19ce31f1e
Revises: 92b5fdb6fcbe
Create Date: 2023-05-19 13:09:55.821975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae19ce31f1e'
down_revision = '92b5fdb6fcbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('digesta_books', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('share', sa.Float(precision=4), nullable=True))
    #
    # with op.batch_alter_table('digesta_tituli', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('share', sa.Float(precision=4), nullable=True))
    #     batch_op.add_column(sa.Column('book_share', sa.Float(precision=4), nullable=True))

    with op.batch_alter_table('opera_book_coverage', schema=None) as batch_op:
        batch_op.create_unique_constraint('abc', ['opus_id', 'book_id'])

    with op.batch_alter_table('opera_titulus_coverage', schema=None) as batch_op:
        batch_op.create_unique_constraint('cda', ['opus_id', 'titulus_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opera_titulus_coverage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('opera_book_coverage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('digesta_tituli', schema=None) as batch_op:
        batch_op.drop_column('book_share')
        batch_op.drop_column('share')

    with op.batch_alter_table('digesta_books', schema=None) as batch_op:
        batch_op.drop_column('share')

    # ### end Alembic commands ###
