"""empty message

Revision ID: 5d62c87df732
Revises: 0d47955dacae
Create Date: 2023-05-18 06:49:15.185359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d62c87df732'
down_revision = '0d47955dacae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulus_authorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('titulus_id', sa.Integer(), nullable=True),
    sa.Column('authorship', sa.Float(precision=4), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['titulus_id'], ['digesta_tituli.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'titulus_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titulus_authorships')
    # ### end Alembic commands ###
