"""empty message

Revision ID: 6fd6b48b45db
Revises: e6a4e52e9214
Create Date: 2023-04-19 16:35:21.999712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd6b48b45db'
down_revision = 'e6a4e52e9214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lex_id', sa.Integer(), nullable=False),
    sa.Column('reply_to_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lex_id'], ['digesta_leges.id'], ),
    sa.ForeignKeyConstraint(['reply_to_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
