"""empty message

Revision ID: 92b5fdb6fcbe
Revises: 5d62c87df732
Create Date: 2023-05-19 08:59:12.145385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b5fdb6fcbe'
down_revision = '5d62c87df732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opera_book_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opus_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Float(precision=4), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['digesta_books.id'], ),
    sa.ForeignKeyConstraint(['opus_id'], ['opera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opera_titulus_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opus_id', sa.Integer(), nullable=True),
    sa.Column('titulus_id', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Float(precision=4), nullable=True),
    sa.ForeignKeyConstraint(['opus_id'], ['opera.id'], ),
    sa.ForeignKeyConstraint(['titulus_id'], ['digesta_tituli.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverage', sa.Float(precision=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opera', schema=None) as batch_op:
        batch_op.drop_column('coverage')

    op.drop_table('opera_titulus_coverage')
    op.drop_table('opera_book_coverage')
    # ### end Alembic commands ###
