"""empty message

Revision ID: aaac78204b2d
Revises: 6fd6b48b45db
Create Date: 2023-04-19 17:35:20.430949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaac78204b2d'
down_revision = '6fd6b48b45db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
