"""empty message

Revision ID: cc5e49a0a8df
Revises: 37bd6a65a29d
Create Date: 2023-05-14 06:08:21.731721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5e49a0a8df'
down_revision = '37bd6a65a29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('paragraphus_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('paragraphus_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
