"""empty message

Revision ID: d75f548b6375
Revises: 2a1d55c4b60b
Create Date: 2023-05-06 23:53:06.587645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75f548b6375'
down_revision = '2a1d55c4b60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digesta_leges', schema=None) as batch_op:
        batch_op.alter_column('lex_nr',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digesta_leges', schema=None) as batch_op:
        batch_op.alter_column('lex_nr',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
