"""empty message

Revision ID: dcd33a84f9e2
Revises: 
Create Date: 2023-04-15 05:49:57.353837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd33a84f9e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('flourished_start', sa.Integer(), nullable=True),
    sa.Column('flourished_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('digesta_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_latin_name', sa.String(length=256), nullable=False),
    sa.Column('book_polish_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_latin_name'),
    sa.UniqueConstraint('book_polish_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('digesta_tituli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title_lat', sa.String(length=256), nullable=False),
    sa.Column('title_pl', sa.String(length=256), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['digesta_books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'book_id')
    )
    op.create_table('opera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_lat', sa.String(length=256), nullable=False),
    sa.Column('title_pl', sa.String(length=256), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_lat', 'author_id', 'book')
    )
    op.create_table('digesta_leges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_lat', sa.Text(), nullable=False),
    sa.Column('address_pl', sa.Text(), nullable=False),
    sa.Column('text_lat', sa.Text(), nullable=False),
    sa.Column('text_pl', sa.Text(), nullable=False),
    sa.Column('lex_nr', sa.Integer(), nullable=False),
    sa.Column('titulus_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('opus_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['digesta_books.id'], ),
    sa.ForeignKeyConstraint(['opus_id'], ['opera.id'], ),
    sa.ForeignKeyConstraint(['titulus_id'], ['digesta_tituli.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lex_nr', 'titulus_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lex_id'], ['digesta_leges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('digesta_leges')
    op.drop_table('opera')
    op.drop_table('digesta_tituli')
    op.drop_table('users')
    op.drop_table('digesta_books')
    op.drop_table('authors')
    # ### end Alembic commands ###
