"""empty message

Revision ID: e6a4e52e9214
Revises: 42e185668598
Create Date: 2023-04-18 15:33:45.376628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a4e52e9214'
down_revision = '42e185668598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('lex_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('lex_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
