"""empty message

Revision ID: b3b965e95643
Revises: 967805e8b268
Create Date: 2023-05-27 11:37:32.788024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b965e95643'
down_revision = '967805e8b268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('authorship',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('authorships', schema=None) as batch_op:
        batch_op.alter_column('authorship',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('digesta_books', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('digesta_tituli', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
        batch_op.alter_column('book_share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('opera', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('opera_book_coverage', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('opera_titulus_coverage', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('titulus_authorships', schema=None) as batch_op:
        batch_op.alter_column('authorship',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titulus_authorships', schema=None) as batch_op:
        batch_op.alter_column('authorship',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('opera_titulus_coverage', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('opera_book_coverage', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('opera', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('digesta_tituli', schema=None) as batch_op:
        batch_op.alter_column('book_share',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('digesta_books', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('authorships', schema=None) as batch_op:
        batch_op.alter_column('authorship',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('authorship',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
